# Generated by Django 5.1.1 on 2024-10-05 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=30)),
                ('total_amount', models.FloatField()),
                ('customer_adress', models.CharField(max_length=100)),
            ],
        ),
    ]
